# Generated by Django 3.2.4 on 2021-10-04 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211004_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroImage', models.ImageField(default='', upload_to='screenshots/')),
                ('logo', models.ImageField(default='', upload_to='screenshots/')),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 4, 22, 18, 5, 58801)),
        ),
    ]
